app:
  cors:
    allowed-origins: http://10.147.20.1:80
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  datasource:
    url: jdbc:postgresql://localhost:5432/event_app
    username: app
    password: app
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-phlbwuivnwgq0kxl.us.auth0.com/
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  address: 10.147.20.1
  port: 80
  #address: 10.147.20.1
  #port: 80
  error:
    include-message: always

auth0:
  audience: https://eventap-api/